Be a Volunteer 💙
uoosef/cf-bepass pull request #6
Opened 2023-08-24 21:59 UTC by Ptechgithub

Install and automatic add IP to the domain

2023-08-26 16:14 UTC, DanielcoderX commented on volunteer.sh
> +            zone_id="98dc00aea2fe235d9f3b08ec2f5932f2"  # Replace with your actual zone ID
Also modify this and take these from the user

2023-08-26 16:28 UTC, DanielcoderX commented on volunteer.sh
> +            api_token="NnO5sXHbIaW03qxZFeBlnOCJH30g9ore_Q0Xu2qm"  # Replace with your actual API token
Also modify this to get the value from the user

2023-08-26 16:29 UTC, DanielcoderX commented on volunteer.sh
> +            email="onlycloudflare@gmail.com"  # Replace with your actual email
this too

2023-08-26 16:29 UTC, DanielcoderX commented on volunteer.sh
> +            subdomain="iran"
again this too

2023-08-26 16:31 UTC, DanielcoderX requested changes
Hi, Ptechgithub.
**Thanks** for your interest in contributing and helping us for further improvements.
for some reasons, please build by `trimming path` and getting a `release` also disabling `CGO`.
_Here_ is the fixed build command: `CGO_ENABLED=0 go build -ldflags '-s -w' -trimpath ./relay.go`
Also please fix those that I've mention at the conversation.

2023-08-28 13:12 UTC, DanielcoderX commented
Hi again.
Thanks for fixing the build process, but as I mentioned, this part should get fixed and get filled by the user when running the script.

```
            # Cloudflare API variables
            zone_id="98dc00aea2fe235d9f3b08ec2f5932f2"  # Replace with your actual zone ID
            api_token="NnO5sXHbIaW03qxZFeBlnOCJH30g9ore_Q0Xu2qm"  # Replace with your actual API token
            email="onlycloudflare@gmail.com"  # Replace with your actual email
            subdomain="iran"
```

Also there's no need to get the output with name _relay_release_, just a normal **relay** is ok.

2023-08-28 19:50 UTC, Ptechgithub commented
If this section is edited, anyone who wants to donate a server must also donate a domain.  But you can choose a default domain and the servers will be behind that domain.  The domain included in this code is iran.ptechfree.eu.org

2023-08-28 19:58 UTC, DanielcoderX commented
> If this section is edited, anyone who wants to donate a server must also donate a domain.  But you can choose a default domain and the servers will be behind that domain.  The domain included in this code is iran.ptechfree.eu.org.
> 
> 
> While the server can be added with an A RECORD and there is no need for the user's zone ID and apk token.  You can place a domain and if the number of volunteer servers increases, add some servers to another domain through Cloudflare.

Alright, Let's merge it :)

2023-08-28 19:58 UTC, merged